version: '3'
services:
  app1:
    build: .
    container_name: node-app-1
    # Не пробрасываем порт наружу!
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/sports_events_db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run dev

  app2:
    build: .
    container_name: node-app-2
    # Не пробрасываем порт наружу!
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/sports_events_db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run dev

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"

volumes:
  mongo_data: